language: clojure
lein: lein2
before_script:
  - 'echo "Memcached version:"'
  - 'echo stats | nc 127.0.0.1 11211 | grep version | sed s/STAT//'
script: lein2 all test
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
